### Login
# @name login
POST {{host}}/auth/login
content-type: application/json

{
  "username": "user2",
	"password": "12345678"
}
###

@myAccessToken = {{login.response.body.accessToken}}

### Create products
POST {{host}}/products
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{ 

    "name": "Product new 66",
    "price": 100,
    "image": "https://example.com/avatar.jpg",
    "description": "This is a product description"
}

### Get All Products
GET {{host}}/products
authorization: Bearer {{myAccessToken}}

### Get Product By Id
GET {{host}}/products/5b33cbbe-8294-4083-9a4c-981f6bd08533
authorization: Bearer {{myAccessToken}}

### Delete Product By Id
DELETE {{host}}/products/5efeac2d-ef72-4ebe-a851-48f0e6b8fca8
authorization: Bearer {{myAccessToken}}

### Update Product By Id
PUT {{host}}/products/5b33cbbe-8294-4083-9a4c-981f6bd08533
Content-Type: application/json
authorization: Bearer {{myAccessToken}}

{
    "name": "Product new 99 update",
    "price": 1000,
    "image": "https://example.com/avatar.jpg",
    "description": "This is a product description"
}